[client]
toolbarMode = "minimal"
showErrorDetails = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#FFD700"
backgroundColor = "#080405"
secondaryBackgroundColor = "#1f0f12"
textColor = "#f8fafc"
